language: node_js
node_js:
  - 0.6

before_script:
  - npm install grunt-cli
  - grunt build

script:
  - npm test

notifications:
  irc:
    - "irc.freenode.org#iks"
    - "irc.freenode.org#midgard"
