language: node_js
node_js:
  - 0.6

before_script:
  - npm install --dev

script:
  - ./node_modules/.bin/jshint examples/create.js
  - npm test

notifications:
  irc:
    - "irc.freenode.org#iks"
    - "irc.freenode.org#midgard"
